server:
  port: 9527

spring:
  application:
    name: ordersystem-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/
  instance:
    instance-id:  ordersystem-zuul-gateway-9527
    prefer-ip-address: true


zuul:
#  ignored-services: microservicecloud-dept  # 将真是服务名忽略
  prefix: /idea
  ignored-services: "*" # 将所有微服务忽略
  routes:
    dishes.serviceId: ordersystem-dishes
    mydept.path: /dishes/**

info:
  app.name: idea-ordersystem
  company.name: www.idea-a.com.cn
  build.artifactId: $project.artifactId$
  build.version: $project.version$
